os: unstable
#atrix:
# - build: msvc2010
#   QTDIR:
#   make: nmake release
install:
# - set QTDIR=C:\Qt\5.5\mingw492_32
 - set QTDIR=C:\Qt\5.13.2\msvc2017_64
 - set PATH=%PATH%;%QTDIR%\bin
# - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
 - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
 - qmake liloucalc.pro
 - nmake release
 - cd release
