image: Visual Studio 2017

# See https://www.appveyor.com/docs/windows-images-software/#qt
environment:
  matrix:
    #- QTDIR: C:\Qt\5.6.3\mingw49_32
    #- QTDIR: C:\Qt\5.6.3\msvc2015
    #- QTDIR: C:\Qt\5.6.3\msvc2015_64
    #- QTDIR: C:\Qt\5.7\mingw53_32
    #- QTDIR: C:\Qt\5.7\msvc2015
    #- QTDIR: C:\Qt\5.9\mingw53_32
    #- QTDIR: C:\Qt\5.9\msvc2015
    #- QTDIR: C:\Qt\5.9\msvc2015_64
    #- QTDIR: C:\Qt\5.10\mingw53_32
    #- QTDIR: C:\Qt\5.10\msvc2015
    #- QTDIR: C:\Qt\5.10\msvc2015_64
    #- QTDIR: C:\Qt\5.11\mingw53_32
    #- QTDIR: C:\Qt\5.11\msvc2015
    #- QTDIR: C:\Qt\5.11\msvc2015_64
    #- QTDIR: C:\Qt\5.12.5\mingw73_64
    #- QTDIR: C:\Qt\5.12.5\mingw73_32
    #- QTDIR: C:\Qt\5.12.5\msvc2015_64
    - QTDIR: C:\Qt\5.13.2\mingw73_64
    - QTDIR: C:\Qt\5.13.2\msvc2017_64

configuration:
  #- debug
   - release

init:
  - git config --global core.autocrlf input

install:
  # Setup the build toolchains
  - cmd: vcpkg integrate install
  - cmd: vcpkg install gsl:x64-windows
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2017=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  # Prepare the out-of-source build directory
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'

