branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.11.0\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake liloucalc.pro
  - mingw32-make
