image: Visual Studio 2017

clone_folder: C:\projects\sheep-qt
shallow_clone: true
cache: c:\tools\vcpkg\installed\

# See https://www.appveyor.com/docs/windows-images-software/#qt
environment:
  matrix:
    #- QTDIR: C:\Qt\5.6.3\mingw49_32
    #- QTDIR: C:\Qt\5.6.3\msvc2015
    #- QTDIR: C:\Qt\5.6.3\msvc2015_64
    #- QTDIR: C:\Qt\5.7\mingw53_32
    #- QTDIR: C:\Qt\5.7\msvc2015
    #- QTDIR: C:\Qt\5.9\mingw53_32
    #- QTDIR: C:\Qt\5.9\msvc2015
    #- QTDIR: C:\Qt\5.9\msvc2015_64
    #- QTDIR: C:\Qt\5.10\mingw53_32
    #- QTDIR: C:\Qt\5.10\msvc2015
    #- QTDIR: C:\Qt\5.10\msvc2015_64
    #- QTDIR: C:\Qt\5.11\mingw53_32
    #- QTDIR: C:\Qt\5.11\msvc2015
    #- QTDIR: C:\Qt\5.11\msvc2015_64
    #- QTDIR: C:\Qt\5.12.5\mingw73_64
    #- QTDIR: C:\Qt\5.12.5\mingw73_32
    #- QTDIR: C:\Qt\5.12.5\msvc2015_64
    #- QTDIR: C:\Qt\5.13.2\mingw73_64
    #- QTDIR: C:\Qt\5.13.2\mingw73_32
    - QTDIR: C:\Qt\5.13.2\msvc2017
    - QTDIR: C:\Qt\5.13.2\msvc2017_64

configuration:
  - debug
  # - release

init:
  - git config --global core.autocrlf input

install:
  # Setup the build toolchains
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2017=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul
  - vcpkg install gsl
  - vcpkg integrate install

before_build:
  # Prepare the out-of-source build directory
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DPLEIONE_DOC=OFF -DPLEIONE_PERF=ON -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% -DCMAKE_CXX_FLAGS="/wd4275 /wd4251"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'
