version: 0.9.{build}

environment:
  matrix:
    - QTDIR: C:\Qt\5.13.2\mingw73_64
      cname: mingw

configuration:
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %cname%==mingw set make=mingw32-make.exe
  - if %cname%==mingw g++ --version
  - if %cname%==mingw %make% --version
  - if not %cname%==mingw call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %cname%==mingw set make=nmake.exe
  - if not %cname%==mingw %make% /? > nul

before_build:
  - if %cname%==mingw set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - '%make%'
   #Also, build vcxproj (without qt)

